server:
  port: 8080

# JPA
spring:
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        hbm2ddl:
          auto: update
    show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://35.77.202.110:3306/petplace
    username: devuser
    password: qwer!@34


oauth2:
  jwt:
    secret-key: ALSDFJAWIEJDSLFJSDKFAEOSPWOREIQEIRTOERGJKFBMXMVXLDKFSEORIWORTJLDFASDMCXVMZXKLVJKEJIAJDKFKJSDFJKASDKJFHEI
    expiration: 604800000
  google:
    client-id: 663371736991-3gjbva9d64mplielt3m14ji527q4ihad.apps.googleusercontent.com

